# Generated by Django 6.0.3 on 2026-04-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם לקוח')),
                ('phone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם מוצר')),
                ('product_code', models.CharField(max_length=100, unique=True, verbose_name='קוד מוצר')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='כמות במלאי')),
                ('description', models.TextField(blank=True, null=True, verbose_name='תיאור')),
            ],
        ),
    ]
