# Generated by Django 6.0.3 on 2026-04-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJcarparts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='הערות')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AJcarparts.customer', verbose_name='לקוח')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='כמות')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר ליחידה')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AJcarparts.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AJcarparts.product', verbose_name='מוצר')),
            ],
        ),
    ]
