# Generated by Django 6.0.3 on 2026-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJcarparts', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'טיוטה'), ('completed', 'הושלמה'), ('printed', 'הודפסה'), ('delivered', 'נמסרה'), ('cancelled', 'בוטלה')], default='draft', max_length=20, verbose_name='סטטוס'),
        ),
    ]
