# Generated by Django 6.0.3 on 2026-04-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJcarparts', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_updated',
            field=models.BooleanField(default=False, verbose_name='מלאי עודכן'),
        ),
    ]
