# Generated by Django 6.0.3 on 2026-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJcarparts', '0005_order_stock_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='כתובת'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ע.מ / ח.פ'),
        ),
    ]
