# Generated by Django 6.0.3 on 2026-04-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJcarparts', '0006_customer_address_customer_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='הנחה (%)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AJcarparts.order', verbose_name='הזמנה'),
        ),
    ]
