# Generated by Django 6.0.3 on 2026-04-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJcarparts', '0008_alter_orderitem_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='נמסרה'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='הודפסה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'טיוטה'), ('completed', 'הושלמה'), ('cancelled', 'בוטלה')], default='draft', max_length=20, verbose_name='סטטוס'),
        ),
    ]
